function buildExportHtml({ title = 'Investigation Snapshot', nodes = [], edges = [], exportedAt = new Date() }) {
  const rows = nodes.map(n => `
    <tr>
      <td style="padding:8px;border:1px solid #ddd;font-family:Arial">${n.address}</td>
      <td style="padding:8px;border:1px solid #ddd;font-family:Arial">${n.label || ''}</td>
      <td style="padding:8px;border:1px solid #ddd;font-family:Arial">${n.type || ''}</td>
      <td style="padding:8px;border:1px solid #ddd;font-family:Arial">${n.risk_score ?? ''}</td>
    </tr>
  `).join('\n');

  const edgeRows = edges.map(e => `
    <tr>
      <td style="padding:8px;border:1px solid #ddd;font-family:Arial">${e.from_address || e.from}</td>
      <td style="padding:8px;border:1px solid #ddd;font-family:Arial">${e.to_address || e.to}</td>
      <td style="padding:8px;border:1px solid #ddd;font-family:Arial">${e.relation}</td>
      <td style="padding:8px;border:1px solid #ddd;font-family:Arial">${e.tx_count ?? ''}</td>
      <td style="padding:8px;border:1px solid #ddd;font-family:Arial">${e.total_value ?? ''}</td>
    </tr>
  `).join('\n');

  return `
  <!doctype html>
  <html>
  <head>
    <meta charset="utf-8" />
    <title>${title}</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <style>
      body { font-family: Arial, Helvetica, sans-serif; color: #111; }
      .header { background: linear-gradient(90deg,#5b21b6,#0ea5a4); color: #fff; padding: 20px; }
      .container { padding: 20px; }
      table { border-collapse: collapse; width: 100%; margin-bottom: 20px; }
      th { text-align: left; padding: 8px; background: #f3f4f6; border: 1px solid #ddd; }
    </style>
  </head>
  <body>
    <div class="header">
      <h1 style="margin:0">${title}</h1>
      <div style="font-size:12px;margin-top:6px">Exported at: ${exportedAt.toISOString()}</div>
    </div>
    <div class="container">
      <h2>Nodes</h2>
      <table>
        <thead>
          <tr>
            <th>Address</th>
            <th>Label</th>
            <th>Type</th>
            <th>Risk Score</th>
          </tr>
        </thead>
        <tbody>
          ${rows || '<tr><td colspan="4" style="padding:8px;border:1px solid #ddd">No nodes</td></tr>'}
        </tbody>
      </table>

      <h2>Edges</h2>
      <table>
        <thead>
          <tr>
            <th>From</th>
            <th>To</th>
            <th>Relation</th>
            <th>Tx Count</th>
            <th>Total Value</th>
          </tr>
        </thead>
        <tbody>
          ${edgeRows || '<tr><td colspan="5" style="padding:8px;border:1px solid #ddd">No edges</td></tr>'}
        </tbody>
      </table>

      <div style="font-size:12px;color:#666">Generated by CryptoIntelX</div>
    </div>
  </body>
  </html>
  `;
}

module.exports = { buildExportHtml };
